# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'FMI App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMI App
  pod 'Firebase/Core', '5.2.0'
  pod 'Firebase/Auth', '5.2.0'
  pod 'MarkdownView', '1.5.0'
end
